/**
 * Lista completă a țărilor (ISO 3166-1 alpha-2) cu numele în română + alias în
 * engleză pentru căutare. GENERAT cu `Intl.DisplayNames` (locale "ro"/"en"),
 * sortat alfabetic după numele românesc. Folosit de selectorul de naționalitate.
 *
 * În câmpul `nationality` se salvează CODUL ISO2 (ex. "MD", "RO") — canonic și
 * stabil. Afișarea rezolvă codul înapoi la nume + steag prin `findCountry`.
 */
export interface Country {
  /** Cod ISO 3166-1 alpha-2, UPPERCASE (ex. "MD"). */
  code: string;
  /** Numele țării în română (pentru afișare). */
  name: string;
  /** Numele în engleză (alias suplimentar pentru căutare). */
  nameEn: string;
}

export const COUNTRIES: readonly Country[] = [
  { code: "AF", name: "Afganistan", nameEn: "Afghanistan" },
  { code: "ZA", name: "Africa de Sud", nameEn: "South Africa" },
  { code: "AL", name: "Albania", nameEn: "Albania" },
  { code: "DZ", name: "Algeria", nameEn: "Algeria" },
  { code: "AD", name: "Andorra", nameEn: "Andorra" },
  { code: "AO", name: "Angola", nameEn: "Angola" },
  { code: "AG", name: "Antigua și Barbuda", nameEn: "Antigua & Barbuda" },
  { code: "SA", name: "Arabia Saudită", nameEn: "Saudi Arabia" },
  { code: "AR", name: "Argentina", nameEn: "Argentina" },
  { code: "AM", name: "Armenia", nameEn: "Armenia" },
  { code: "AU", name: "Australia", nameEn: "Australia" },
  { code: "AT", name: "Austria", nameEn: "Austria" },
  { code: "AZ", name: "Azerbaidjan", nameEn: "Azerbaijan" },
  { code: "BS", name: "Bahamas", nameEn: "Bahamas" },
  { code: "BH", name: "Bahrain", nameEn: "Bahrain" },
  { code: "BD", name: "Bangladesh", nameEn: "Bangladesh" },
  { code: "BB", name: "Barbados", nameEn: "Barbados" },
  { code: "BY", name: "Belarus", nameEn: "Belarus" },
  { code: "BE", name: "Belgia", nameEn: "Belgium" },
  { code: "BZ", name: "Belize", nameEn: "Belize" },
  { code: "BJ", name: "Benin", nameEn: "Benin" },
  { code: "BT", name: "Bhutan", nameEn: "Bhutan" },
  { code: "BO", name: "Bolivia", nameEn: "Bolivia" },
  { code: "BA", name: "Bosnia și Herțegovina", nameEn: "Bosnia & Herzegovina" },
  { code: "BW", name: "Botswana", nameEn: "Botswana" },
  { code: "BR", name: "Brazilia", nameEn: "Brazil" },
  { code: "BN", name: "Brunei", nameEn: "Brunei" },
  { code: "BG", name: "Bulgaria", nameEn: "Bulgaria" },
  { code: "BF", name: "Burkina Faso", nameEn: "Burkina Faso" },
  { code: "BI", name: "Burundi", nameEn: "Burundi" },
  { code: "KH", name: "Cambodgia", nameEn: "Cambodia" },
  { code: "CM", name: "Camerun", nameEn: "Cameroon" },
  { code: "CA", name: "Canada", nameEn: "Canada" },
  { code: "CV", name: "Capul Verde", nameEn: "Cape Verde" },
  { code: "CZ", name: "Cehia", nameEn: "Czechia" },
  { code: "CL", name: "Chile", nameEn: "Chile" },
  { code: "CN", name: "China", nameEn: "China" },
  { code: "TD", name: "Ciad", nameEn: "Chad" },
  { code: "CY", name: "Cipru", nameEn: "Cyprus" },
  { code: "CO", name: "Columbia", nameEn: "Colombia" },
  { code: "KM", name: "Comore", nameEn: "Comoros" },
  { code: "CG", name: "Congo - Brazzaville", nameEn: "Congo - Brazzaville" },
  { code: "CD", name: "Congo - Kinshasa", nameEn: "Congo - Kinshasa" },
  { code: "KP", name: "Coreea de Nord", nameEn: "North Korea" },
  { code: "KR", name: "Coreea de Sud", nameEn: "South Korea" },
  { code: "CR", name: "Costa Rica", nameEn: "Costa Rica" },
  { code: "CI", name: "Côte d’Ivoire", nameEn: "Côte d’Ivoire" },
  { code: "HR", name: "Croația", nameEn: "Croatia" },
  { code: "CU", name: "Cuba", nameEn: "Cuba" },
  { code: "DK", name: "Danemarca", nameEn: "Denmark" },
  { code: "DJ", name: "Djibouti", nameEn: "Djibouti" },
  { code: "DM", name: "Dominica", nameEn: "Dominica" },
  { code: "EC", name: "Ecuador", nameEn: "Ecuador" },
  { code: "EG", name: "Egipt", nameEn: "Egypt" },
  { code: "SV", name: "El Salvador", nameEn: "El Salvador" },
  { code: "CH", name: "Elveția", nameEn: "Switzerland" },
  { code: "AE", name: "Emiratele Arabe Unite", nameEn: "United Arab Emirates" },
  { code: "ER", name: "Eritreea", nameEn: "Eritrea" },
  { code: "EE", name: "Estonia", nameEn: "Estonia" },
  { code: "SZ", name: "Eswatini", nameEn: "Eswatini" },
  { code: "ET", name: "Etiopia", nameEn: "Ethiopia" },
  { code: "FJ", name: "Fiji", nameEn: "Fiji" },
  { code: "PH", name: "Filipine", nameEn: "Philippines" },
  { code: "FI", name: "Finlanda", nameEn: "Finland" },
  { code: "FR", name: "Franța", nameEn: "France" },
  { code: "GA", name: "Gabon", nameEn: "Gabon" },
  { code: "GM", name: "Gambia", nameEn: "Gambia" },
  { code: "GE", name: "Georgia", nameEn: "Georgia" },
  { code: "DE", name: "Germania", nameEn: "Germany" },
  { code: "GH", name: "Ghana", nameEn: "Ghana" },
  { code: "GR", name: "Grecia", nameEn: "Greece" },
  { code: "GD", name: "Grenada", nameEn: "Grenada" },
  { code: "GT", name: "Guatemala", nameEn: "Guatemala" },
  { code: "GN", name: "Guineea", nameEn: "Guinea" },
  { code: "GQ", name: "Guineea Ecuatorială", nameEn: "Equatorial Guinea" },
  { code: "GW", name: "Guineea-Bissau", nameEn: "Guinea-Bissau" },
  { code: "GY", name: "Guyana", nameEn: "Guyana" },
  { code: "HT", name: "Haiti", nameEn: "Haiti" },
  { code: "HN", name: "Honduras", nameEn: "Honduras" },
  { code: "IN", name: "India", nameEn: "India" },
  { code: "ID", name: "Indonezia", nameEn: "Indonesia" },
  { code: "MH", name: "Insulele Marshall", nameEn: "Marshall Islands" },
  { code: "SB", name: "Insulele Solomon", nameEn: "Solomon Islands" },
  { code: "JO", name: "Iordania", nameEn: "Jordan" },
  { code: "IQ", name: "Irak", nameEn: "Iraq" },
  { code: "IR", name: "Iran", nameEn: "Iran" },
  { code: "IE", name: "Irlanda", nameEn: "Ireland" },
  { code: "IS", name: "Islanda", nameEn: "Iceland" },
  { code: "IL", name: "Israel", nameEn: "Israel" },
  { code: "IT", name: "Italia", nameEn: "Italy" },
  { code: "JM", name: "Jamaica", nameEn: "Jamaica" },
  { code: "JP", name: "Japonia", nameEn: "Japan" },
  { code: "KZ", name: "Kazahstan", nameEn: "Kazakhstan" },
  { code: "KG", name: "Kârgâzstan", nameEn: "Kyrgyzstan" },
  { code: "KE", name: "Kenya", nameEn: "Kenya" },
  { code: "KI", name: "Kiribati", nameEn: "Kiribati" },
  { code: "XK", name: "Kosovo", nameEn: "Kosovo" },
  { code: "KW", name: "Kuweit", nameEn: "Kuwait" },
  { code: "LA", name: "Laos", nameEn: "Laos" },
  { code: "LS", name: "Lesotho", nameEn: "Lesotho" },
  { code: "LV", name: "Letonia", nameEn: "Latvia" },
  { code: "LB", name: "Liban", nameEn: "Lebanon" },
  { code: "LR", name: "Liberia", nameEn: "Liberia" },
  { code: "LY", name: "Libia", nameEn: "Libya" },
  { code: "LI", name: "Liechtenstein", nameEn: "Liechtenstein" },
  { code: "LT", name: "Lituania", nameEn: "Lithuania" },
  { code: "LU", name: "Luxemburg", nameEn: "Luxembourg" },
  { code: "MK", name: "Macedonia de Nord", nameEn: "North Macedonia" },
  { code: "MG", name: "Madagascar", nameEn: "Madagascar" },
  { code: "MW", name: "Malawi", nameEn: "Malawi" },
  { code: "MY", name: "Malaysia", nameEn: "Malaysia" },
  { code: "MV", name: "Maldive", nameEn: "Maldives" },
  { code: "ML", name: "Mali", nameEn: "Mali" },
  { code: "MT", name: "Malta", nameEn: "Malta" },
  { code: "MA", name: "Maroc", nameEn: "Morocco" },
  { code: "MR", name: "Mauritania", nameEn: "Mauritania" },
  { code: "MU", name: "Mauritius", nameEn: "Mauritius" },
  { code: "MX", name: "Mexic", nameEn: "Mexico" },
  { code: "FM", name: "Micronezia", nameEn: "Micronesia" },
  { code: "MC", name: "Monaco", nameEn: "Monaco" },
  { code: "MN", name: "Mongolia", nameEn: "Mongolia" },
  { code: "MZ", name: "Mozambic", nameEn: "Mozambique" },
  { code: "ME", name: "Muntenegru", nameEn: "Montenegro" },
  { code: "MM", name: "Myanmar (Birmania)", nameEn: "Myanmar (Burma)" },
  { code: "NA", name: "Namibia", nameEn: "Namibia" },
  { code: "NR", name: "Nauru", nameEn: "Nauru" },
  { code: "NP", name: "Nepal", nameEn: "Nepal" },
  { code: "NI", name: "Nicaragua", nameEn: "Nicaragua" },
  { code: "NE", name: "Niger", nameEn: "Niger" },
  { code: "NG", name: "Nigeria", nameEn: "Nigeria" },
  { code: "NO", name: "Norvegia", nameEn: "Norway" },
  { code: "NZ", name: "Noua Zeelandă", nameEn: "New Zealand" },
  { code: "OM", name: "Oman", nameEn: "Oman" },
  { code: "PK", name: "Pakistan", nameEn: "Pakistan" },
  { code: "PW", name: "Palau", nameEn: "Palau" },
  { code: "PA", name: "Panama", nameEn: "Panama" },
  { code: "PG", name: "Papua-Noua Guinee", nameEn: "Papua New Guinea" },
  { code: "PY", name: "Paraguay", nameEn: "Paraguay" },
  { code: "PE", name: "Peru", nameEn: "Peru" },
  { code: "PL", name: "Polonia", nameEn: "Poland" },
  { code: "PT", name: "Portugalia", nameEn: "Portugal" },
  { code: "QA", name: "Qatar", nameEn: "Qatar" },
  { code: "HK", name: "R.A.S. Hong Kong, China", nameEn: "Hong Kong SAR China" },
  { code: "MO", name: "R.A.S. Macao, China", nameEn: "Macao SAR China" },
  { code: "GB", name: "Regatul Unit", nameEn: "United Kingdom" },
  { code: "CF", name: "Republica Centrafricană", nameEn: "Central African Republic" },
  { code: "DO", name: "Republica Dominicană", nameEn: "Dominican Republic" },
  { code: "MD", name: "Republica Moldova", nameEn: "Moldova" },
  { code: "RO", name: "România", nameEn: "Romania" },
  { code: "RU", name: "Rusia", nameEn: "Russia" },
  { code: "RW", name: "Rwanda", nameEn: "Rwanda" },
  { code: "KN", name: "Saint Kitts și Nevis", nameEn: "St. Kitts & Nevis" },
  { code: "VC", name: "Saint Vincent și Grenadinele", nameEn: "St. Vincent & Grenadines" },
  { code: "WS", name: "Samoa", nameEn: "Samoa" },
  { code: "SM", name: "San Marino", nameEn: "San Marino" },
  { code: "ST", name: "São Tomé și Príncipe", nameEn: "São Tomé & Príncipe" },
  { code: "SN", name: "Senegal", nameEn: "Senegal" },
  { code: "RS", name: "Serbia", nameEn: "Serbia" },
  { code: "SC", name: "Seychelles", nameEn: "Seychelles" },
  { code: "LC", name: "Sfânta Lucia", nameEn: "St. Lucia" },
  { code: "SL", name: "Sierra Leone", nameEn: "Sierra Leone" },
  { code: "SG", name: "Singapore", nameEn: "Singapore" },
  { code: "SY", name: "Siria", nameEn: "Syria" },
  { code: "SK", name: "Slovacia", nameEn: "Slovakia" },
  { code: "SI", name: "Slovenia", nameEn: "Slovenia" },
  { code: "SO", name: "Somalia", nameEn: "Somalia" },
  { code: "ES", name: "Spania", nameEn: "Spain" },
  { code: "LK", name: "Sri Lanka", nameEn: "Sri Lanka" },
  { code: "US", name: "Statele Unite ale Americii", nameEn: "United States" },
  { code: "VA", name: "Statul Cetății Vaticanului", nameEn: "Vatican City" },
  { code: "SD", name: "Sudan", nameEn: "Sudan" },
  { code: "SS", name: "Sudanul de Sud", nameEn: "South Sudan" },
  { code: "SE", name: "Suedia", nameEn: "Sweden" },
  { code: "SR", name: "Suriname", nameEn: "Suriname" },
  { code: "TJ", name: "Tadjikistan", nameEn: "Tajikistan" },
  { code: "TW", name: "Taiwan", nameEn: "Taiwan" },
  { code: "TZ", name: "Tanzania", nameEn: "Tanzania" },
  { code: "PS", name: "Teritoriile Palestiniene", nameEn: "Palestinian Territories" },
  { code: "TH", name: "Thailanda", nameEn: "Thailand" },
  { code: "TL", name: "Timor-Leste", nameEn: "Timor-Leste" },
  { code: "TG", name: "Togo", nameEn: "Togo" },
  { code: "TO", name: "Tonga", nameEn: "Tonga" },
  { code: "TT", name: "Trinidad și Tobago", nameEn: "Trinidad & Tobago" },
  { code: "TN", name: "Tunisia", nameEn: "Tunisia" },
  { code: "TR", name: "Turcia", nameEn: "Türkiye" },
  { code: "TM", name: "Turkmenistan", nameEn: "Turkmenistan" },
  { code: "TV", name: "Tuvalu", nameEn: "Tuvalu" },
  { code: "NL", name: "Țările de Jos", nameEn: "Netherlands" },
  { code: "UA", name: "Ucraina", nameEn: "Ukraine" },
  { code: "UG", name: "Uganda", nameEn: "Uganda" },
  { code: "HU", name: "Ungaria", nameEn: "Hungary" },
  { code: "UY", name: "Uruguay", nameEn: "Uruguay" },
  { code: "UZ", name: "Uzbekistan", nameEn: "Uzbekistan" },
  { code: "VU", name: "Vanuatu", nameEn: "Vanuatu" },
  { code: "VE", name: "Venezuela", nameEn: "Venezuela" },
  { code: "VN", name: "Vietnam", nameEn: "Vietnam" },
  { code: "YE", name: "Yemen", nameEn: "Yemen" },
  { code: "ZM", name: "Zambia", nameEn: "Zambia" },
  { code: "ZW", name: "Zimbabwe", nameEn: "Zimbabwe" },
];

/**
 * Rezolvă o valoare salvată în `nationality` la o țară cunoscută.
 * Acceptă: cod ISO2 (nou), numele RO sau EN (valori vechi, text liber).
 * Întoarce `undefined` dacă valoarea nu se potrivește cu nicio țară.
 */
export function findCountry(value?: string | null): Country | undefined {
  if (!value) return undefined;
  const v = value.trim().toLowerCase();
  if (!v) return undefined;
  return COUNTRIES.find(
    (c) =>
      c.code.toLowerCase() === v ||
      c.name.toLowerCase() === v ||
      c.nameEn.toLowerCase() === v,
  );
}

/** Filtrează țările după un termen de căutare (nume RO sau EN, ori cod). */
export function searchCountries(query: string): readonly Country[] {
  const q = query.trim().toLowerCase();
  if (!q) return COUNTRIES;
  return COUNTRIES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.nameEn.toLowerCase().includes(q) ||
      c.code.toLowerCase() === q,
  );
}
