"""deferred message and reaction columns

Revision ID: 1bcd6214fd44
Revises: 164b16936bbd
Create Date: 2026-07-07 10:00:43.308472
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1bcd6214fd44'
down_revision: Union[str, None] = '164b16936bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('deferred_message', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('reaction', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reaction')
    op.drop_column('likes', 'deferred_message')
    # ### end Alembic commands ###
