"""events attendance passport

Revision ID: 348f5f8aecf9
Revises: 7b7229e487a0
Create Date: 2026-07-07 07:23:46.550434
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '348f5f8aecf9'
down_revision: Union[str, None] = '7b7229e487a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_attendances',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('going', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_attendance_pair')
    )
    op.create_index(op.f('ix_event_attendances_event_id'), 'event_attendances', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_attendances_user_id'), 'event_attendances', ['user_id'], unique=False)
    op.create_table('flirt_passport_stamps',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stamped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_stamp_pair')
    )
    op.create_index(op.f('ix_flirt_passport_stamps_event_id'), 'flirt_passport_stamps', ['event_id'], unique=False)
    op.create_index(op.f('ix_flirt_passport_stamps_user_id'), 'flirt_passport_stamps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flirt_passport_stamps_user_id'), table_name='flirt_passport_stamps')
    op.drop_index(op.f('ix_flirt_passport_stamps_event_id'), table_name='flirt_passport_stamps')
    op.drop_table('flirt_passport_stamps')
    op.drop_index(op.f('ix_event_attendances_user_id'), table_name='event_attendances')
    op.drop_index(op.f('ix_event_attendances_event_id'), table_name='event_attendances')
    op.drop_table('event_attendances')
    op.drop_table('events')
    # ### end Alembic commands ###
