"""profile verified column

Revision ID: 64f32c9f9dad
Revises: c1792e250ccf
Create Date: 2026-07-07 22:06:48.050411
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64f32c9f9dad'
down_revision: Union[str, None] = 'c1792e250ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'verified')
    # ### end Alembic commands ###
